language: node_js
node_js:
  - "10.16.0"
cache:
  directories:
    - /api/node_modules
    - /app/node_modules

before_install:
  - cd api && npm install
  - cd .. && cd app && yarn

script:
  - cd api && npm run build
  - cd .. && cd app && yarn build

branches:
  only:
    - master
