language: node_js
node_js:
  - "10.16.0"
cache:
  directories:
    - /api/node_modules
    - /app/node_modules

before_install:
  - cd api && npm install
  - cd .. && cd app && yarn

script:
  - yarn build
  - cd .. && cd api && npm run build

branches:
  only:
    - master

after_success:
  - npm run test
  - cd .. && cd app && yarn test
