version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
  app:
    build: .
    command: npm run start
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
volumes:
  database_data:
